server:
  port: 8081

spring:
  application:
    name: cloud-payment-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource     #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver         #mysql驱动包
    url: jdbc:mysql://loaclhost:3306/cloud0801db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: password

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities   #所有entity别名类所在包

